stanzas:
  - type: webapp
    exec: ../kucipong
    host: stage.kucipong.com
    env:
      KUCIPONG_HOST: "stage.kucipong.com"
      KUCIPONG_PROTOCOL: "https"
      KUCIPONG_MAILGUN_DOMAIN: "stage.kucipong.com"
      ENV: Production
    forward-env:
      - KUCIPONG_DB_PASSWORD
      - KUCIPONG_MAILGUN_APIKEY
